# ===============================
# 1. ПОДКЛЮЧЕНИЕ К БАЗЕ ДАННЫХ (Neon PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-weathered-frog-alll0rle.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JnuVNmXa2cS8
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# 2. НАСТРОЙКИ HIBERNATE (Управление таблицами)
# ===============================
# update - Spring Boot будет сам создавать и обновлять таблицы в базе!
spring.jpa.hibernate.ddl-auto=update
# Показывать SQL-запросы в консоли (очень полезно для отладки)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# 3. НАСТРОЙКИ СЕРВЕРА
# ===============================
server.port=8080